### ISSUE TITLE
感谢大佬开源，关注大佬很久了，视频都是跪着看完的~~

### ISSUE THREAD

**Issue by luxunchina** [peng-zhihui/L-ink_Card#1]
这个迷你NFC卡片超酷的啊，有木有？可以复制任意卡片的功能我真是酸了，好想有一个，奈何动手能力极差，希望各位关注此项目的老板做好后给个链接，我想直接买个成品，跪谢~

**Comment by WHYEX3** [comment]
3分钟前？readme热乎乎

**Comment by San12341** [comment]
我也想直接买成品。

**Comment by WHYEX3** [comment]
> 我也想直接买成品。

+1，如果教程我能看懂的话且成本低，我想自己搞一个

**Comment by peng-zhihui** [comment]
感谢关注~项目也还是有一些不完善的地方的，后面有空我会继续更新方案的哈

**Comment by ahdiua** [comment]
> 感谢关注~项目也还是有一些不完善的地方的，后面有空我会继续更新方案的哈

三连啦，就等大佬发教程

**Comment by XenoAmess** [comment]
> 感谢关注~项目也还是有一些不完善的地方的，后面有空我会继续更新方案的哈

硬件和C我这边帮不上忙
如果安卓端放源码的话 可以试试。。。

**Comment by xdeng** [comment]
求成品链接，我要买十个。急需。

**Comment by peng-zhihui** [comment]
不属于Issue的不要发在这里哈~
