### ISSUE TITLE
大佬求教

### ISSUE THREAD

**Issue by Shuhaoalex** [peng-zhihui/L-ink_Card#10]
大佬我是CS专业的，有编程方面的能力，但看你的项目还是一脸懵逼。想求教一下如果想从零基础开始到能设计出像这样的项目，大概需要怎么去点科技树。。。。

**Comment by XenoAmess** [comment]
目测主要得点单片机相关的技能点
如果你模电和数电课学的很开心的话可以考虑深入。。。
反正我是放弃硬件了233

**Comment by peng-zhihui** [comment]
这个可以看一下我往期的视频和知乎的文章，不属于Issue的不要发在这里哈
