### ISSUE TITLE
关于IC卡兼容问题

### ISSUE THREAD

**Issue by DMB-codegang** [peng-zhihui/L-ink_Card#112]
大佬，我是一个高中生，想用您这个设备复制我的饭卡和门禁卡。我想问一下这个设备支持MANGO的MF1S50EV1吗，我在网上没找到信息

**Comment by Rulsion** [comment]
已收到，放心

**Comment by DMB-codegang** [comment]
21年的issue，我现在已经大二了哈哈哈哈哈哈
