### ISSUE TITLE
请教请教！有没有已经完全做好了这个项目的？

### ISSUE THREAD

**Issue by qinzhongle** [peng-zhihui/L-ink_Card#132]
我是一名大一学生 现在已经放寒假了 想请教一下 怎么完成这个项目 尤其是加密卡读写那一方面 如果你们看到了这个留言 我很期待你们能给我一个回复！

**Comment by qinzhongle** [comment]
comecome!

**Comment by Horldsence** [comment]
我也是大一新生，现在也在复刻，或许有机会可以交流下。
_刚买完所有器件（淘宝和立创商城），外壳3D打印的，板子嘉立创打。('ヮ')_

**Comment by Rulsion** [comment]
已收到，放心

**Comment by Horldsence** [comment]
> comecome!

我也是大一新生，现在也在复刻，或许有机会可以交流下。
_刚买完所有器件（淘宝和立创商城），外壳3D打印的，板子嘉立创打。('ヮ')_

**Comment by jeremylee1** [comment]
> > comecome!
> 
> 我也是大一新生，现在也在复刻，或许有机会可以交流下。 _刚买完所有器件（淘宝和立创商城），外壳3D打印的，板子嘉立创打。('ヮ')_

我找了下很多都买不到 能分享一下零件的购买链接么。我也是想拿这个项目练练手

**Comment by Rulsion** [comment]
已收到，放心

**Comment by Rulsion** [comment]
已收到，放心
