### ISSUE TITLE
我用立创app导入,报错UTF-8编码问题

### ISSUE THREAD

**Issue by wangbokun** [peng-zhihui/L-ink_Card#14]
文件需为UTF-8编码的ASCII格式文件，这个可以调整吗

**Comment by liangling11411** [comment]
这个用AD打开没什么问题，我用我用立创导入也有编码问题

**Comment by peng-zhihui** [comment]
找个AD软件转换一下吧，立创的我没怎么用过

**Comment by wangbokun** [comment]
用AD软件的话，硬件去哪里下单制作， 因为立创有在线下单定做硬件，比较方便,对于我这种小白用户而言.

**Comment by BH6AOV** [comment]
utf-8的ASCII在 #17 
打样的话导出pcb设计文件给商家就行

**Comment by wangbokun** [comment]
a

> utf-8的ASCII在 #17
> 打样的话导出pcb设计文件给商家就行
老哥666，我去试试.
