### ISSUE TITLE
啊 这个实在是太好玩了   我要尝试做一个试试

### ISSUE THREAD

**Issue by qi765235401** [peng-zhihui/L-ink_Card#18]
膜拜大佬！

**Comment by hwdef** [comment]
这种无意义的issue。。。。为什么要发呢。。。

**Comment by XenoAmess** [comment]
> 这种无意义的issue。。。。为什么要发呢。。。

因为作者做了个视频到B站。。。
然后B站用户怎么说呢小孩子挺多的2333

**Comment by hwdef** [comment]
@XenoAmess 
如果是因为做视频发到了b站的话，，，这种“啊 这个实在是太好玩了 我要尝试做一个试试”，发到视频评论也行啊。。。。
为什么要来污染issue呢。。。。。

**Comment by peng-zhihui** [comment]
项目无关的问题不要发Issue哈，看来我得去readme说明一下...
