### ISSUE TITLE
关于复制加密M1卡的问题

### ISSUE THREAD

**Issue by BH6AOV** [peng-zhihui/L-ink_Card#19]
请问大佬，有些加密了的手机无法复制的那种M1卡要如何复制啊，手持PN532。家里小区门禁卡手机没法复制，fcuk也跑不动

**Comment by hwdef** [comment]
仔细看视频，加密卡不能复制是因为手机系统限制，，，这个开源硬件并没有限制。。。。另外不是这个开源硬件相关的问题发到issue里也不好吧。。

**Comment by BH6AOV** [comment]
是的，现在的问题不是说问如何复制，问的是怎么复制进L-ink。
在 #7 里up提到用的是PM3和PN532，配套也就是fcuk来跑，问题是有的加密的卡fcuk是跑不出来的

**Comment by peng-zhihui** [comment]
拿不到原卡数据的话可能没办法，可以换个设备试试看，我用PM3目前是没有遇到过解不出的卡的

**Comment by BH6AOV** [comment]
> 拿不到原卡数据的话可能没办法，可以换个设备试试看，我用PM3目前是没有遇到过解不出的卡的

感谢解答，回头我去试试
