### ISSUE TITLE
大佬能否分享一下android app工程文件

### ISSUE THREAD

**Issue by hanjianwei92** [peng-zhihui/L-ink_Card#2]
大佬能否分享一下app的工程文件

**Comment by baolintian** [comment]
+1

**Comment by peng-zhihui** [comment]
> 大佬能否分享一下app的工程文件

工程文件的话因为这是我以前做的一个框架改的，而这个框架有用在我们公司的项目里面，所以不知道好不好分享出来。不过我后面可以把其中的核心功能模块封装成库，然后给个Sample Project供参考，等我忙过这阵子吧。

**Comment by bosssyyyy** [comment]
大佬能否上传一下ASCII版本的ad文件，目前没有购买安装ad无法转换文件类型
