### ISSUE TITLE
关于S1的型号

### ISSUE THREAD

**Issue by irongu** [peng-zhihui/L-ink_Card#21]
bom和sch中都没有s1的准确型号，在某宝上搜了一下拨轮开关、滚轮开关之类的关键词，找到的都是编码器或者有定位柱的自复位开关，明显与footprint不符。
所以请问能否提供一下s1的型号或者更详细的描述，以便于正确的找到对应元件，谢谢。

**Comment by peng-zhihui** [comment]
搜 拨轮开关

fu至本段内容₴6jlF1EYHktZ₴咑幵👉淘tao寳👈或点几炼接https://m.tb.cn/h.VLnWz3Z?sm=e9f89f 至流览器【MP3 MP4 手机 拨轮按键 小头拨轮开关 6脚贴片开关 (2个)】
