### ISSUE TITLE
STM32L051和ST25DV的具体型号

### ISSUE THREAD

**Issue by Lauv-who** [peng-zhihui/L-ink_Card#22]
我在官网看到有很多型号，不知道要买哪个[](url)
![ST25DV64K - 64-Kbit ](https://user-images.githubusercontent.com/60261857/85361701-3259a100-b54f-11ea-9987-d46f7ef0d2c1.png)
![STM32L051C8](https://user-images.githubusercontent.com/60261857/85361703-3685be80-b54f-11ea-85a6-c7dc19207c28.png)希望能解答下，谢谢

**Comment by wangbokun** [comment]
> 我在官网看到有很多型号，不知道要买哪个
> ![ST25DV64K - 64-Kbit ](https://user-images.githubusercontent.com/60261857/85361701-3259a100-b54f-11ea-9987-d46f7ef0d2c1.png)
> ![STM32L051C8](https://user-images.githubusercontent.com/60261857/85361703-3685be80-b54f-11ea-85a6-c7dc19207c28.png)希望能解答下，谢谢

大佬，你这个是在哪里下单的呢.我也准备弄一个.

**Comment by Lauv-who** [comment]
> > 我在官网看到有很多型号，不知道要买哪个
> 
> > ![ST25DV64K - 64-Kbit ](https://user-images.githubusercontent.com/60261857/85361701-3259a100-b54f-11ea-9987-d46f7ef0d2c1.png)
> 
> > ![STM32L051C8](https://user-images.githubusercontent.com/60261857/85361703-3685be80-b54f-11ea-85a6-c7dc19207c28.png)希望能解答下，谢谢
> 
> 
> 
> 大佬，你这个是在哪里下单的呢.我也准备弄一个.

我没下单，不知道能不能买以及购买数量的限制，产地是有中国的

**Comment by Teng-NUKE** [comment]
BOM表里有具体型号和封装

**Comment by Lauv-who** [comment]
> BOM表里有具体型号和封装

谢谢

**Comment by peng-zhihui** [comment]
ST25DV64K，STM32L051K8U6

**Comment by peng-zhihui** [comment]
> 我在官网看到有很多型号，不知道要买哪个
> ![ST25DV64K - 64-Kbit ](https://user-images.githubusercontent.com/60261857/85361701-3259a100-b54f-11ea-9987-d46f7ef0d2c1.png)
> ![STM32L051C8](https://user-images.githubusercontent.com/60261857/85361703-3685be80-b54f-11ea-85a6-c7dc19207c28.png)希望能解答下，谢谢

ST25DV64K，STM32L051K8U6

**Comment by Lauv-who** [comment]
> > 我在官网看到有很多型号，不知道要买哪个
> > ![ST25DV64K - 64-Kbit ](https://user-images.githubusercontent.com/60261857/85361701-3259a100-b54f-11ea-9987-d46f7ef0d2c1.png)
> > ![STM32L051C8](https://user-images.githubusercontent.com/60261857/85361703-3685be80-b54f-11ea-85a6-c7dc19207c28.png)希望能解答下，谢谢
> 
> ST25DV64K，STM32L051K8U6

谢谢大佬

**Comment by doublemarkpro** [comment]
> > 我在官网看到有很多型号，不知道要买哪个
> > ![ST25DV64K - 64-Kbit ](https://user-images.githubusercontent.com/60261857/85361701-3259a100-b54f-11ea-9987-d46f7ef0d2c1.png)
> > ![STM32L051C8](https://user-images.githubusercontent.com/60261857/85361703-3685be80-b54f-11ea-85a6-c7dc19207c28.png)希望能解答下，谢谢
> 
> ST25DV64K，STM32L051K8U6

您好，看原理图RFID芯片用的是ST25DV16K，这里您回复又是64K，以哪个为准呢?

**Comment by peng-zhihui** [comment]
> > > 我在官网看到有很多型号，不知道要买哪个
> > > ![ST25DV64K - 64-Kbit ](https://user-images.githubusercontent.com/60261857/85361701-3259a100-b54f-11ea-9987-d46f7ef0d2c1.png)
> > > ![STM32L051C8](https://user-images.githubusercontent.com/60261857/85361703-3685be80-b54f-11ea-85a6-c7dc19207c28.png)希望能解答下，谢谢
> > 
> > 
> > ST25DV64K，STM32L051K8U6
> 
> 您好，看原理图RFID芯片用的是ST25DV16K，这里您回复又是64K，以哪个为准呢?

其实都可以，区别只是EEPROM大小不同而已，最好是买64K哈

**Comment by doublemarkpro** [comment]
> > > > 我在官网看到有很多型号，不知道要买哪个
> > > > ![ST25DV64K - 64-Kbit ](https://user-images.githubusercontent.com/60261857/85361701-3259a100-b54f-11ea-9987-d46f7ef0d2c1.png)
> > > > ![STM32L051C8](https://user-images.githubusercontent.com/60261857/85361703-3685be80-b54f-11ea-85a6-c7dc19207c28.png)希望能解答下，谢谢
> > > 
> > > 
> > > ST25DV64K，STM32L051K8U6
> > 
> > 
> > 您好，看原理图RFID芯片用的是ST25DV16K，这里您回复又是64K，以哪个为准呢?
> 
> 其实都可以，区别只是EEPROM大小不同而已，最好是买64K哈

好的，元器件已买，pcb自己简单修改了一下已经交去做板，3d打印也交给第三方做去了，另外请教一下，您b站视频中的最后是盖上了一块亚克力外壳吗？这个有无开源尺寸图呢？厚度需要做几个毫米的？谢谢。

**Comment by Lauv-who** [comment]
> > > > > 我在官网看到有很多型号，不知道要买哪个
> 
> > > > > ![ST25DV64K - 64-Kbit ](https://user-images.githubusercontent.com/60261857/85361701-3259a100-b54f-11ea-9987-d46f7ef0d2c1.png)
> 
> > > > > ![STM32L051C8](https://user-images.githubusercontent.com/60261857/85361703-3685be80-b54f-11ea-85a6-c7dc19207c28.png)希望能解答下，谢谢
> 
> > > > 
> 
> > > > 
> 
> > > > ST25DV64K，STM32L051K8U6
> 
> > > 
> 
> > > 
> 
> > > 您好，看原理图RFID芯片用的是ST25DV16K，这里您回复又是64K，以哪个为准呢?
> 
> > 
> 
> > 其实都可以，区别只是EEPROM大小不同而已，最好是买64K哈
> 
> 
> 
> 好的，元器件已买，pcb自己简单修改了一下已经交去做板，3d打印也交给第三方做去了，另外请教一下，您b站视频中的最后是盖上了一块亚克力外壳吗？这个有无开源尺寸图呢？厚度需要做几个毫米的？谢谢。

大佬在哪里配的单呀，找了很多家都配不齐，谢谢
