### ISSUE TITLE
pcb挖槽位置

### ISSUE THREAD

**Issue by Lauv-who** [peng-zhihui/L-ink_Card#24]
这个在哪开呀![阿里旺旺图片20200623205955](https://user-images.githubusercontent.com/60261857/85406548-8e92e400-b594-11ea-95b3-ef40668d007c.jpg)

**Comment by peng-zhihui** [comment]
IC0和IC1右边那两个框

**Comment by Lauv-who** [comment]
> IC0和IC1右边那两个框

了解，谢谢

**Comment by Lauv-who** [comment]
> IC0和IC1右边那两个框

店家说文件没有体现挖空的😥大佬给看下
![阿里旺旺图片20200623212724](https://user-images.githubusercontent.com/60261857/85409408-58576380-b598-11ea-970c-8ed064e88efa.jpg)

**Comment by wangbokun** [comment]
我也遇到同样的问题，店家说需要PCB文件上有开槽，才可以，

**Comment by fengboo** [comment]
大佬的PCB上只放了一个board cutout的多边形，没用keepout或机械层画边界，工厂只认keepout或机械层边界，多边形没用。

**Comment by Lauv-who** [comment]
> 大佬的PCB上只放了一个board cutout的多边形，没用keepout或机械层画边界，工厂只认keepout或机械层边界，多边形没用。

这我也不会画呀😂小白太难了

**Comment by wangbokun** [comment]
![image](https://user-images.githubusercontent.com/5212569/85510342-c5ffa000-b629-11ea-89fd-d43f94d98f02.png)
不知道这个是不是挖槽成功
