### ISSUE TITLE
两个不同网络元素间距小于设计规则DRC的距离

### ISSUE THREAD

**Issue by wangbokun** [peng-zhihui/L-ink_Card#25]
大佬，请教下,这种间距问题怎么做调整.

![image](https://user-images.githubusercontent.com/5212569/85427927-02da8100-b5af-11ea-8a48-96ebce15139f.png)

**Comment by Sorakage033** [comment]
建议修改设计规则（

**Comment by wangbokun** [comment]
嗯，我还是放弃了，下载了ad来编辑
