### ISSUE TITLE
板子在线下单参数请教

### ISSUE THREAD

**Issue by wangbokun** [peng-zhihui/L-ink_Card#26]
![image](https://user-images.githubusercontent.com/5212569/85485098-ac932f80-b5fa-11ea-91f9-e4a5b33f011d.png)
麻烦问下，这些选项怎么选
板子尺寸: ?
厚度: ?
阻焊覆盖:?
焊盘喷镀： ?
铜厚度:?
金手指是否要斜边:?

**Comment by peng-zhihui** [comment]
> ![image](https://user-images.githubusercontent.com/5212569/85485098-ac932f80-b5fa-11ea-91f9-e4a5b33f011d.png)
> 麻烦问下，这些选项怎么选
> 板子尺寸: ?
> 厚度: ?
> 阻焊覆盖:?
> 焊盘喷镀： ?
> 铜厚度:?
> 金手指是否要斜边:?

全部默认就行

**Comment by wangbokun** [comment]
长宽不能默认，我猜了个长4cm宽3m不知道对不对.

**Comment by GeorgeMicro** [comment]
板子宽度（cm）： | 3.7 | 板子长度（cm）： | 4.7
嘉立创审核之后是这样的
