### ISSUE TITLE
墨水屏盖板

### ISSUE THREAD

**Issue by Lauv-who** [peng-zhihui/L-ink_Card#27]
盖板是亚克力的吗？具体尺寸是多少，以及开孔的位置，谢谢大佬💪

**Comment by peng-zhihui** [comment]
盖板1mm的切割就行了，外壳我设计地比较简单没有开孔，用B-7000胶水粘合的（这是粘手机屏幕的胶，二次开启后可以不留残胶挺好用的）

**Comment by Lauv-who** [comment]
> 盖板1mm的切割就行了，外壳我设计地比较简单没有开孔，用B-7000胶水粘合的（这是粘手机屏幕的胶，二次开启后可以不留残胶挺好用的）

谢谢

**Comment by csr865** [comment]
请问pcb图在哪，，

**Comment by Lauv-who** [comment]
> 请问pcb图在哪，，

请认真阅读项目文件说明

Hardware：source里面是电路原理图和PCB文件，使用Altium Designer打开；release里面是gerber文件可以直接发给厂家打样，也包含了元器件BOM表（部分IC不太常用可能要单独购买）。
