### ISSUE TITLE
Q1的MOS管和贴片滑轮有无具体型号？

### ISSUE THREAD

**Issue by doublemarkpro** [peng-zhihui/L-ink_Card#28]
BOM上的Q1没有具体型号，另外滑轮我看pcb是贴片的，有具体型号吗？

**Comment by liangling11411** [comment]
麻烦看一下已经closed的issue，里面都有人问了
https://github.com/peng-zhihui/L-ink_Card/issues/21
https://github.com/peng-zhihui/L-ink_Card/issues/23
