### ISSUE TITLE
开槽位置请教

### ISSUE THREAD

**Issue by wangbokun** [peng-zhihui/L-ink_Card#29]
![image](https://user-images.githubusercontent.com/5212569/85504973-c8f59300-b61f-11ea-9210-fdfd44204dab.png)
是在这个位置开槽吗？ 看到下面有蓝色的条，可以直接在这里开槽吗？

**Comment by liangling11411** [comment]
![ST8`{FE`90GG4_SE0Y49DM3](https://user-images.githubusercontent.com/60998714/85508863-71f3bc00-b627-11ea-82e5-ef5247ae8a16.png)
是这里（黄笔圈的地方），你直接这样说就行了
![09D5CDA2C3663FE81E114952E209CE26](https://user-images.githubusercontent.com/60998714/85508906-8e8ff400-b627-11ea-848c-66413766a926.jpg)
预览图：（圈住的地方开槽）
![J%H@~Y}L6S{`W0VL%@8Z$9U](https://user-images.githubusercontent.com/60998714/85508963-a8c9d200-b627-11ea-88a9-7b2ba6b6b8c0.png)

**Comment by Lauv-who** [comment]
> ![ST8`{FE`90GG4_SE0Y49DM3](https://user-images.githubusercontent.com/60998714/85508863-71f3bc00-b627-11ea-82e5-ef5247ae8a16.png)
> 
> 是这里（黄笔圈的地方），你直接这样说就行了
> 
> ![09D5CDA2C3663FE81E114952E209CE26](https://user-images.githubusercontent.com/60998714/85508906-8e8ff400-b627-11ea-848c-66413766a926.jpg)
> 
> 预览图：（圈住的地方开槽）
> 
> ![J%H@~Y}L6S{`W0VL%@8Z$9U](https://user-images.githubusercontent.com/60998714/85508963-a8c9d200-b627-11ea-88a9-7b2ba6b6b8c0.png)
> 
> 

在嘉立创下单的话 上传release还是source都可以吗？上传后的具体参数能不能发个图看一下小白不太懂 谢谢

**Comment by liangling11411** [comment]
![)RFV`8J`Q}~ @Q0~DFT($6S](https://user-images.githubusercontent.com/60998714/85509426-956b3680-b628-11ea-870f-66fa5091a52d.png)
是release文件夹下的gerber文件夹，把里面的东西打成压缩包（.zip/.rar)
直接发给pcb生产厂家就行了
我的话没有买钢网，如果焊工不好可以整个钢网辅助一下
![9EA77DE14E2ECEE6D952307C321F657F](https://user-images.githubusercontent.com/60998714/85509846-3659f180-b629-11ea-996f-73205c13b637.jpg)

**Comment by Lauv-who** [comment]
> ![)RFV`8J`Q}~ @Q0~DFT($6S](https://user-images.githubusercontent.com/60998714/85509426-956b3680-b628-11ea-870f-66fa5091a52d.png)
> 
> 是release文件夹下的gerber文件夹，把里面的东西打成压缩包（.zip/.rar)
> 
> 直接发给pcb生产厂家就行了
> 
> 我的话没有买钢网，如果焊工不好可以整个钢网辅助一下
> 
> ![9EA77DE14E2ECEE6D952307C321F657F](https://user-images.githubusercontent.com/60998714/85509846-3659f180-b629-11ea-996f-73205c13b637.jpg)
> 
> 

谢谢您，因为我是小白，所以打算同时下单smt焊接

**Comment by liangling11411** [comment]
嗯嗯，玩的开心，没问题了就把issue close一下吧（右下角）

**Comment by Lauv-who** [comment]
> 嗯嗯，玩的开心，没问题了就把issue close一下吧（右下角）

谢谢，这个不是我发的issue😀

**Comment by wangbokun** [comment]
挖槽那个事情怎么弄的？就给客服说一下就行？不用该文件吗？

**Comment by liangling11411** [comment]
> 挖槽那个事情怎么弄的？就给客服说一下就行？不用该文件吗？
先把Gerber文件交给厂家，到时候厂家会回问你开槽的事，你直接说IC0和IC1右边两个框开槽就行了
![85508906-8e8ff400-b627-11ea-848c-66413766a926](https://user-images.githubusercontent.com/60998714/85520615-bc7c3500-b635-11ea-99cd-e5ca80f934b1.jpg)

**Comment by wangbokun** [comment]
好的，明白了，多谢多谢，
