### ISSUE TITLE
纯小白，能不能告诉下芯片是不是要写东西进去啊，怎么写进去啊？

### ISSUE THREAD

**Issue by minemc24236** [peng-zhihui/L-ink_Card#30]
如题O(∩_∩)O

**Comment by peng-zhihui** [comment]
百度一下吧，用jlink或者stlink下载，或者等后面出详细教程（如果有哪个同学实践过程有空写教程也可以联系我帮你发出来~）

**Comment by csr865** [comment]
请问下手机上怎么下载文件夹

**Comment by minemc24236** [comment]
用电脑吧，软件什么的都是电脑的，手机没法用的

**Comment by csr865** [comment]
我想问下用什么刷固件名字型号发下谢谢了

**Comment by jiangyou233** [comment]
> 我想问下用什么刷固件名字型号发下谢谢了

天… 我这怎么收到了邮件提醒……  有问题不要这里留言啦   主控用的STM32  需要STLINK 或者Jlink dap下载器进行下载……

**Comment by iwtywai** [comment]
up不是发了dap-link的软硬件吗，所以为什么不自己找找

**Comment by iwtywai** [comment]
就在同一个项目里

**Comment by jiangyou233** [comment]
> 就在同一个项目里

别了 别了 还是纯小白还是买一个下载器吧  这个DAP还是需要下载固件的…… 到时候DAP焊接调试劝退

**Comment by iwtywai** [comment]
> > 就在同一个项目里
> 
> 别了 别了 还是纯小白还是买一个下载器吧 这个DAP还是需要下载固件的…… 到时候DAP焊接调试劝退
淘宝十几块 调试爽歪歪
