### ISSUE TITLE
关于Q1和U3的型号问题

### ISSUE THREAD

**Issue by Skylarrkuo** [peng-zhihui/L-ink_Card#32]
请问Q1用SI2318DS，U3用TPS61221DCKR可以吗

**Comment by Skylarrkuo** [comment]
还有就是电容的电压应该怎么选，淘宝上同一uf有不同的电压（小白一枚）

**Comment by TaXue-DuBa** [comment]
电容电压指的是最大耐压值。。差不多的就可

**Comment by TaXue-DuBa** [comment]
> 还有就是电容的电压应该怎么选，淘宝上同一uf有不同的电压（小白一枚）

电容电压指的是最大耐压值。。差不多的就可以

**Comment by iwtywai** [comment]
Mosfet只要是N-都行
电容耐压5V以上

**Comment by peng-zhihui** [comment]
LDO只要输出电压一致就行，电容在这个应用中所有型号都能满足，因为工作电压很低（3.3V）
