### ISSUE TITLE
UID硬件连接

### ISSUE THREAD

**Issue by 782884341** [peng-zhihui/L-ink_Card#37]
如何把uid芯片集成在PCB上，是可以直接焊在ST25DV的引脚上面和NFC公用天线吗

**Comment by iwtywai** [comment]
![image](https://user-images.githubusercontent.com/25090836/85911703-36403880-b859-11ea-8574-fef42c8eadc3.jpg)如果我没有理解错的话，应该是中间这两个开窗的位置

**Comment by 782884341** [comment]
那如果要扩展更多的卡，是不是得要修改PCB，增加UID位

**Comment by iwtywai** [comment]
emmm好像是，毕竟up也说这个st25dv模拟不了15xxx的卡，所以模拟完全是靠共用天线的芯片实现的

**Comment by peng-zhihui** [comment]
对的，可以自己添加uid的卡位，不用考虑线圈遮挡整个背面都是可以添加的。另外下一版我会加入软件模拟IC功能，卡多的话建议等后续更新。
