### ISSUE TITLE
关于导出Gerber

### ISSUE THREAD

**Issue by BH6AOV** [peng-zhihui/L-ink_Card#38]
在立创上用UTF-8存的ASCII的pcb设计文件准备导出gerber去打样了，但是发现网络和DRC有一大堆报错，是直接忽略就行吗
![SharedScreenshot](https://user-images.githubusercontent.com/30193867/85913906-80321a00-b86b-11ea-8904-0ca861d3e946.jpg)
![SharedScreenshot2](https://user-images.githubusercontent.com/30193867/85913908-81fbdd80-b86b-11ea-91e2-e8c0c814436a.jpg)

**Comment by iwtywai** [comment]
在Hardware文件夹有up给的gerber啊

**Comment by BH6AOV** [comment]
> 在Hardware文件夹有up给的gerber啊

立创打不开的

**Comment by BH6AOV** [comment]
> 在Hardware文件夹有up给的gerber啊

具体见#17

**Comment by iwtywai** [comment]
找个打板的把gerber扔过去就行

**Comment by BH6AOV** [comment]
> 找个打板的把gerber扔过去就行

我试试直接扔下单助手上

**Comment by iwtywai** [comment]
记得打包.zip

**Comment by BH6AOV** [comment]
> 记得打包.zip

妥

**Comment by BH6AOV** [comment]
> 找个打板的把gerber扔过去就行

立创那边直接gerber解析超时了

**Comment by iwtywai** [comment]
可以多试几次，或者直接在淘宝找一家打板，我是在淘宝打的

**Comment by BH6AOV** [comment]
> 可以多试几次，或者直接在淘宝找一家打板，我是在淘宝打的

多少钱啊。。。我能给PCB的预算非常少

**Comment by iwtywai** [comment]
我打的无铅黑油，50元5张板

**Comment by minemc24236** [comment]
立创5元的，50打针土豪

**Comment by minemc24236** [comment]
我是像楼主你这么打的，我看报错是地线和天线，也就没管而且就5元吗，大不了再打一版awa

**Comment by iwtywai** [comment]
（我当时打板子gerber文件up还没传，所以用不了jlc）

**Comment by ZKLgayhub** [comment]
1.图1,底层贴片层多出来的开窗要在底层阻焊层开上窗吗 2，图2，箭头位的锣槽输出文件仅在底层字符层有框，就按底层字符层框的大小5*4MM锣出方槽吧

求问，是PCB厂家发过来的，本人小白完全不懂

![阿里旺旺图片20200627160455](https://user-images.githubusercontent.com/51996600/85917802-f8123b80-b88f-11ea-8b65-45ff6aa99e4f.png)
![阿里旺旺图片20200627160458](https://user-images.githubusercontent.com/51996600/85917803-f9436880-b88f-11ea-8601-0618415f04bb.png)

**Comment by BH6AOV** [comment]
> 1.图1,底层贴片层多出来的开窗要在底层阻焊层开上窗吗 2，图2，箭头位的锣槽输出文件仅在底层字符层有框，就按底层字符层框的大小5*4MM锣出方槽吧
> 
> 求问，是PCB厂家发过来的，本人小白完全不懂
> 
> ![阿里旺旺图片20200627160455](https://user-images.githubusercontent.com/51996600/85917802-f8123b80-b88f-11ea-8b65-45ff6aa99e4f.png)
> ![阿里旺旺图片20200627160458](https://user-images.githubusercontent.com/51996600/85917803-f9436880-b88f-11ea-8601-0618415f04bb.png)

@peng-zhihui

**Comment by BH6AOV** [comment]
> 1.图1,底层贴片层多出来的开窗要在底层阻焊层开上窗吗 2，图2，箭头位的锣槽输出文件仅在底层字符层有框，就按底层字符层框的大小5*4MM锣出方槽吧
> 
> 求问，是PCB厂家发过来的，本人小白完全不懂
> 
> ![阿里旺旺图片20200627160455](https://user-images.githubusercontent.com/51996600/85917802-f8123b80-b88f-11ea-8b65-45ff6aa99e4f.png)
> ![阿里旺旺图片20200627160458](https://user-images.githubusercontent.com/51996600/85917803-f9436880-b88f-11ea-8601-0618415f04bb.png)

#29

**Comment by peng-zhihui** [comment]
解析超市不用管，是嘉立创软件的问题，直接提交确认就行
