### ISSUE TITLE
Gerber文件在嘉立创解析超时

### ISSUE THREAD

**Issue by shaoyu1207** [peng-zhihui/L-ink_Card#39]
up的Gerber文件直接导入立创解析不成功
pcb文件转化成ascll文件发现立创eda里面有很多的报错，请问如何解决
#

**Comment by liangling11411** [comment]
没事啊，直接发过去就行了，报不报错不影响，只要工厂那边能打开就行了（说一嘴，我的也解析不出来，但板子已经打完发货了）

**Comment by BH6AOV** [comment]
#38
