### ISSUE TITLE
main函数里面的所有头文件报错（file not found）是什么原因呀？

### ISSUE THREAD

**Issue by Xuyinsong** [peng-zhihui/L-ink_Card#4]

**Comment by peng-zhihui** [comment]
keil工程还是clion，应该是你工程配置的问题，先保证基础工程（比如新建一个LED点灯工程）能跑通再说。

**Comment by Xuyinsong** [comment]
我用的是clion，就是按照您上次分享的博文配置的，有在板子上试过LED灯和串口是可以的。我下载工程文件后就直接用clion打开的，然后就出现了找不到文件的错误，我是第一次用这个，所以配置的问题不是很明白。

**Comment by peng-zhihui** [comment]
Clion里面tools-cmake-reset cache... 然后重新编译试试看，另外因为芯片是STM32L0，需要在STM32CubeMX软件的首页选择“INSTALL or REMOVE embedded software...”里面安装L0的支持包

**Comment by Xuyinsong** [comment]
可以了，嘿嘿！文件放到桌面就可以编译了，在硬盘的文件夹就会报错，不知道什么原因。

**Comment by orzMaster** [comment]
你是不是放在中文目录下了.

**Comment by Xuyinsong** [comment]
是的，可能是这个原因
