### ISSUE TITLE
R9是贴片的吗？阻值多少？

### ISSUE THREAD

**Issue by Lauv-who** [peng-zhihui/L-ink_Card#40]
![image](https://user-images.githubusercontent.com/60261857/85919458-d61fb580-b89d-11ea-872d-81aee973e5a3.png)

**Comment by iwtywai** [comment]
翻翻pcbdoc啊

**Comment by Lauv-who** [comment]
> 翻翻pcbdoc啊

那个我看不懂😥

**Comment by iwtywai** [comment]
那我来看一眼吧

**Comment by iwtywai** [comment]
我从原理图和bom上看，r9是非接，可以不管

**Comment by Lauv-who** [comment]
> 我从原理图和bom上看，r9是非接，可以不管

谢谢
