### ISSUE TITLE
外壳怎么办啊  有没有帮忙的 我这边可以出邮费和材料费   或者我做好电路板互换！

### ISSUE THREAD

**Issue by jiangyou233** [peng-zhihui/L-ink_Card#42]
我这边不知道怎么加工外壳 有没有互助的呀！

**Comment by shaoyu1207** [comment]
可以3D打印

**Comment by jiangyou233** [comment]
> 可以3D打印

上某宝吗 材料贵吗

**Comment by jiangyou233** [comment]
> 可以3D打印

上某宝吗 东西贵吗……

**Comment by iwtywai** [comment]
十几块的事

**Comment by shaoyu1207** [comment]
不贵，某宝上面直接打印一下就行，有的店铺首单是只要交运费的

**Comment by jiangyou233** [comment]
> 不贵，某宝上面直接打印一下就行，有的店铺首单是只要交运费的

OK感谢 问题关了

**Comment by jiangyou233** [comment]
> 十几块的事

OK感谢 问题关了

**Comment by GeorgeMicro** [comment]
还有兴趣换嘛 我有3D打印机

**Comment by agentZhang** [comment]
> 我这边不知道怎么加工外壳 有没有互助的呀！

您好请问您愿意出电路板吗我想购买一个，或者可不可以给我您的email我们再讨论

**Comment by ruinanzhu** [comment]
未来工厂，几十块钱就能搞定发自我的华为手机-------- 原始邮件 --------发件人： agentZhang ***@***.***>日期： 2022年3月31日周四 19:45收件人： peng-zhihui/L-ink_Card ***@***.***>抄送： Subscribed ***@***.***>主    题： Re: [peng-zhihui/L-ink_Card] 外壳怎么办啊  有没有帮忙的 我这边可以出邮费和材料费   或者我做好电路板互换！ (#42)



我这边不知道怎么加工外壳 有没有互助的呀！



您好请问您愿意出电路板吗我想购买一个，或者可不可以给我您的email我们再讨论

**Comment by agentZhang** [comment]
谢谢您的回复，我这边看了一下未来工厂好像是做3d打印的，这个我不需要，现在想要一个焊好的电路板


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: ruinanzhu ***@***.***&gt;
发送时间: 2022年3月31日 20:06
收件人: peng-zhihui/L-ink_Card ***@***.***&gt;
抄送: agentZhang ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[peng-zhihui/L-ink_Card] 外壳怎么办啊  有没有帮忙的 我这边可以出邮费和材料费   或者我做好电路板互换！ (#42)





 未来工厂，几十块钱就能搞定发自我的华为手机-------- 原始邮件 --------发件人： agentZhang ***@***.***&gt;日期： 2022年3月31日周四 19:45收件人： peng-zhihui/L-ink_Card ***@***.***&gt;抄送： Subscribed ***@***.***&gt;主    题： Re: [peng-zhihui/L-ink_Card] 外壳怎么办啊  有没有帮忙的 我这边可以出邮费和材料费   或者我做好电路板互换！ (#42) 
 
 我这边不知道怎么加工外壳 有没有互助的呀！ 
 
 您好请问您愿意出电路板吗我想购买一个，或者可不可以给我您的email我们再讨论
