### ISSUE TITLE
ST25DV的购买问题

### ISSUE THREAD

**Issue by liangling11411** [peng-zhihui/L-ink_Card#46]
有没有人有ST25DV64K的购买地址，在网上搜都说没货。

**Comment by lewin0301** [comment]
都是20天以后发货

**Comment by lewin0301** [comment]
立创商城有,具体到收货多久不知道

**Comment by liangling11411** [comment]
好不容易在阿里巴巴上找到了，但要10天配货，放出来帮助一下大家吧
【ST25DV16K-JFR6D3【IC RFID TRANSP 13.56MHZ 12UFDFPN】】复制￥zS02ezN96VCap￥，打开【手机阿里】或【支付宝-点首页进行搜索】查看：https://qr.1688.com/share.html?secret=m35uFKSs
