### ISSUE TITLE
请教关于方案设计方面的问题，有关ST25DV、拨轮、天线和开口

### ISSUE THREAD

**Issue by yelvlab** [peng-zhihui/L-ink_Card#47]
> 这个应该不算是无关问题吧，并且不是很懂，特地来请教

### 最大的疑惑：底部两个开口的作用

看底部两个开口旁边还有焊盘，同时看原理图里面给的网络标识是ant，同时接到拨轮里面，这部分没太看懂，请大佬解答下，或者哪里有相关资料

**Comment by im12** [comment]
波轮是一个多入单出的开关，本来ant是闭环的天线，UP切断了加入了开关，平时按下接入的是ST25DV，往一边拨接入中间开孔的一个UID芯片，断开ST25DV，另一边一样，相当于一个线圈天线给多个芯片做天线用
波轮开关的原理图可以参考这个厂家的介绍：http://www.jian-fu.com/product/content?id=664

**Comment by yelvlab** [comment]
嗯，大致明白了，之前不了解要有UID芯片
