### ISSUE TITLE
请问bom表里的跳线是什么样的？

### ISSUE THREAD

**Issue by jikeshen** [peng-zhihui/L-ink_Card#48]
我把bom表给店家，他说没这么小的

**Comment by Blueanr** [comment]
![image](https://user-images.githubusercontent.com/24488292/86103044-db277380-baee-11ea-80bd-0f5f801406c2.png)
![image](https://user-images.githubusercontent.com/24488292/86103086-e5497200-baee-11ea-98d2-cbbd36d0693a.png)
0402的0r电阻这么难买吗？？？
