### ISSUE TITLE
关于L1 2520 68uh电感问题

### ISSUE THREAD

**Issue by asdsartfg** [peng-zhihui/L-ink_Card#51]
找边全网都没有2520磁珠68uh电感，0.68uh的到是有，请问你们是怎么解决的？

**Comment by im12** [comment]
把磁珠去了找吧，2520是绕线电感的规格，磁珠可能没这么大的

**Comment by asdsartfg** [comment]
> 把磁珠去了找吧，2520是绕线电感的规格，磁珠可能没这么大的

问题是，绕线和磁珠不是同一个东西啊

**Comment by im12** [comment]
这个设计中都是作电感用的

**Comment by peng-zhihui** [comment]
https://detail.tmall.com/item.htm?id=35828958171 我是用这个
