### ISSUE TITLE
小伙伴们，来组队一起做啊

### ISSUE THREAD

**Issue by xiaoyun-TaiChi** [peng-zhihui/L-ink_Card#54]
咱么可以组个队。，大多数元器件都无法单独购买。每个人也不都擅长硬件焊接
我们可以分工嘛，有兴趣的可以加群144538834，加群问题，

加群目的=DIY

**Comment by jiangyou233** [comment]
> 咱么可以组个队。，大多数元器件都无法单独购买。每个人也不都擅长硬件焊接
> 我们可以分工嘛，有兴趣的可以加群144538834，加群问题，
> 
> 加群目的=DIY
为啥要弄个加群问题啊 简直多此一举 根本加不进去

**Comment by Skywatch2019** [comment]
楼上的群根本进不去，大家进这个群：983599608  一起来研究吧

**Comment by iwtywai** [comment]
输大写“DIY”不就是了嘛

**Comment by xiaoyun-TaiChi** [comment]
> 楼上的群根本进不去，大家进这个群：983599608一起来研究吧

大写的DIY是不会输入吗？进个群咋都进不来

**Comment by xiaoyun-TaiChi** [comment]
> 咱么可以组个队。，大多数元器件都无法单独购买。每个人也不都擅长硬件焊接
> 我们可以分工嘛，有兴趣的可以加群144538834，加群问题，
> 
> 加群目的= DIY

大写**DIY**

**Comment by Skywatch2019** [comment]
群主不通过  不是我不会输入好么。。。
