### ISSUE TITLE
关于墨水屏和图纸

### ISSUE THREAD

**Issue by BH6AOV** [peng-zhihui/L-ink_Card#55]
请问墨水屏买三色的是不是也可以用？
在微雪官网发现墨水屏有<a href="http://www.waveshare.net/shop/1.54inch-e-Paper.htm">黑白的</a>和<a href="http://www.waveshare.net/shop/1.54inch-e-Paper-B.htm">红黑白三色的</a>两种，而且价格差的并不多，考虑到以后可能的彩色墨水屏兼容我想直接买红黑白三色的，但是不知道能不能用，希望可以解答一下
关联问题 #15 

还有请问方不方便提供一下有元件编号的图纸，焊元件的时候对应不上元件位置有点难受，SchDoc看太不懂（悲）

**Comment by liangling11411** [comment]
第一版不能用彩色墨水屏，因为驱动不一样
元件编号的图纸可以加一下qq群：144538834，（加群问题：加群目的=DIY）里面有大佬画出来了
