### ISSUE TITLE
关于安卓APP

### ISSUE THREAD

**Issue by boxlab** [peng-zhihui/L-ink_Card#57]
请问您有考虑过将安卓APP开源么？希望有机会观摩学习一下

**Comment by TaXue-DuBa** [comment]
> 请问您有考虑过将安卓APP开源么？希望有机会观摩学习一下

不是说那个APP是他们公司的APP吗

**Comment by cy6909** [comment]
想问问为啥我手机用不了这个app呀

**Comment by peng-zhihui** [comment]
这个APP是我做的哈，不过因为有用在公司的项目里面，所以原APP不太好开源，但是我后面会封装好另外一个Sample工程发出来的

**Comment by ruinanzhu** [comment]
> 这个APP是我做的哈，不过因为有用在公司的项目里面，所以原APP不太好开源，但是我后面会封装好另外一个Sample工程发出来的

大佬，能不能给个联系方式，我们众筹凑单批量了一些，想寄给你一个我们做的，我们做了一点点优化
