### ISSUE TITLE
Keil 5程序刷入问题 与 IC_0 IC_1 具体型号问题

### ISSUE THREAD

**Issue by huajijam** [peng-zhihui/L-ink_Card#59]
下载器：Jlink OB 系统:win10 2004 
Jlink OB驱动，stm32L0 前置已下
直接打开"%Project%\Firmware\Keil\L-ink_Card\MDK-ARM\L-ink_Card.uvprojx"点击Flash时报错
![image](https://user-images.githubusercontent.com/29218242/87176684-08ed9300-c30d-11ea-900c-07f6d77f9b65.png)

**Comment by huajijam** [comment]
另 在选购背部IC_0 IC_1时不知如何选择，有成品的大佬劳烦给个建议

**Comment by peng-zhihui** [comment]
1. 先成功编译一遍工程
2. 直接tb搜索UID芯片，有很多
