### ISSUE TITLE
请问怎么把nfc 复制进去???

### ISSUE THREAD

**Issue by Wuanson** [peng-zhihui/L-ink_Card#6]
好像没有看到具体的操作流程,不是按住某个键 ,然后把卡靠近,就可以了????

**Comment by peng-zhihui** [comment]
是使用读卡器读取原卡和复制到L-ink里面的，你可以把L-ink当作一个组合了多张IC白卡的设备，就正常复制就行了。我是使用PM3，也可以买个PN532之类的模块，二十多块钱很便宜的。

**Comment by Wuanson** [comment]
明白了,谢谢大佬讲解.是我理解错了.哈哈哈

**Comment by doube1008** [comment]
> 我是使用PM3，也可以买个PN532之类的模块，二十多块钱很便宜的。

能放个链接么 看淘宝PM3都是大几百的
