### ISSUE TITLE
DAP-LINK

### ISSUE THREAD

**Issue by mumxi** [peng-zhihui/L-ink_Card#60]
想问一下DAP-LINK固件的源码在文件夹中哪一个，有两个hex文件，有大佬知道嘛，请求答疑解惑

**Comment by Fir-Geek** [comment]
一个是bootloader 一个是固件 先刷BL 再把固件拖到DAP-Link的U盘里

**Comment by peng-zhihui** [comment]
参考@Fir-Geek ，是这样的。

**Comment by ultwcz** [comment]
> 想问一下DAP-LINK固件的源码在文件夹中哪一个，有两个hex文件，有大佬知道嘛，

想请教您是如何解决的，我一点思路都没有，一个小白，谢谢。

**Comment by peng-zhihui** [comment]
> > 想问一下DAP-LINK固件的源码在文件夹中哪一个，有两个hex文件，有大佬知道嘛，
> 
> 想请教您是如何解决的，我一点思路都没有，一个小白，谢谢。

建议直接用我另一个仓库的ST-Link Nano，比这个好用
