### ISSUE TITLE
BOM表里面的LDO的疑问

### ISSUE THREAD

**Issue by dremofly** [peng-zhihui/L-ink_Card#61]
BOM的excel文件里面有一个叫做WHEEL_SWITCH的LDO，但是我在原理图和PCB里面似乎都没有见到元件。烦请有经验的大佬指点一下。

**Comment by doublemarkpro** [comment]
那是波轮开关，详见 #21 
并不是叫Switch的都是LDO……八杆子打不着

**Comment by dremofly** [comment]
> 那是波轮开关，详见 #21
> 并不是叫Switch的都是LDO……八杆子打不着

明白了，原来是拨轮开关啊。我就说都有DC-DC converter了，怎么还需要LDO
