### ISSUE TITLE
关于背部IC01 IC02的问题

### ISSUE THREAD

**Issue by Fir-Geek** [peng-zhihui/L-ink_Card#62]
## 关于背部IC01 IC02的问题
不太懂他们俩的意义是什么 
看到有个issue里面提到这句话 对此十分不解
> 背部的两个IC就是门禁卡内部的IC
---
想问一下 **他们俩存在的意义是什么？** 我记得up在视频里提到 L-ink是可以**复制**加密卡的 既然可以复制 何必再装这两个IC呢？
#### 在此先谢过 感激不尽！

**Comment by Blueanr** [comment]
不是复制啊，这个项目就相当于用一个开关切换两张不同卡片，卡片的数据需要你读取出来并自己写入内部的芯片中...其实有点鸡肋

**Comment by Fir-Geek** [comment]
了解了 感谢@Blueanr 的解答
#### 还有一个问题
up在PCB文件中指出，**应该把中间IC的两个槽挖空**，但是我看up**视频中的PCB并没有挖空**
#### 这个何解呢

**Comment by peng-zhihui** [comment]
看readme说明，这一版的设计是这样的；挖空不挖空都可以，因为芯片很薄不影响。

**Comment by Fir-Geek** [comment]
了解了，感谢@peng-zhihui 大佬解答！
