### ISSUE TITLE
关于PCB天线的问题

### ISSUE THREAD

**Issue by stig3** [peng-zhihui/L-ink_Card#63]
按照设计，中间两个IC位置因该是留给自行购买UID芯片焊接上去，然后自己复制IC卡用的
所以，哪怕只焊接这两个IC加一个开关应该也可以使用门禁功能，是这样吧？

另外，看视频的时候，似乎这个天线是针对IC卡13.5MHz频率设计的
那如果我这里焊上两个125K的ID芯片，不知道能不能用？
据我所知，ID卡和IC卡的线圈是不一样的。
有没有人试过？

**Comment by peng-zhihui** [comment]
1. 是的，这一版是可以的，下一版会改用别的方式实现
2. 天线不一样，ID卡线圈密很多，一般很少用PCB天线做，有兴趣的话可以自己留个焊盘焊个天线上去即可，跟IC卡的PCB线圈不冲突。
