### ISSUE TITLE
关于DAP-LINK适用性问题

### ISSUE THREAD

**Issue by mumxi** [peng-zhihui/L-ink_Card#65]
该烧录器是不是只能烧写STM32L0系列的芯片，STM32F7系列不能烧写，求大佬解答，如何更改程序

**Comment by peng-zhihui** [comment]
适用于所有Cortex-M系列芯片，跟Jlink的使用是基本一样的，多了个虚拟 调试串口的功能，以及虚拟U盘拖拽烧录的功能（这个拖拽烧录是只能指定一个芯片的，我这个固件设置的是F103）

**Comment by mumxi** [comment]
稚晖君你好，首先非常感谢您能抽时间答疑解惑，帮助我了解DAP-LINK的相关问题，其次还想问您如果想要指定其他芯片，固件应该怎么改动，万分希望您能指点一下。谢谢，祝您生活愉快，工作顺利！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "peng-zhihui/L-ink_Card"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月22日(星期三) 下午5:25
收件人:&nbsp;"peng-zhihui/L-ink_Card"<L-ink_Card@noreply.github.com&gt;;
抄送:&nbsp;"?哥脫ㄋ，你随意"<2530406776@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [peng-zhihui/L-ink_Card] 关于DAP-LINK适用性问题 (#65)





 
适用于所有Cortex-M系列芯片，跟Jlink的使用是基本一样的，多了个虚拟 调试串口的功能，以及虚拟U盘拖拽烧录的功能（这个拖拽烧录是只能指定一个芯片的，我这个固件设置的是F103）
