### ISSUE TITLE
传输问题

### ISSUE THREAD

**Issue by TopRookie** [peng-zhihui/L-ink_Card#66]
你好，up 可以大概描述下 数据是怎么从手机传输过去的么。通过什么技术呢

**Comment by iwtywai** [comment]
用的是25dv的mailbox功能

**Comment by TopRookie** [comment]
你好 麻烦可以丢些相关连接看下么，刚刚搜了下 maibox好像是邮箱不知道是不是我搜错了，但我看你文档和视频 好像是和NFC 有关


 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "iwtywai"<notifications@github.com&gt;; 
发送时间: 2020年7月23日(星期四) 上午10:24
收件人: "peng-zhihui/L-ink_Card"<L-ink_Card@noreply.github.com&gt;; 
抄送: "wo+"<564528143@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [peng-zhihui/L-ink_Card] 传输问题 (#66)





 用的是25dv的mailbox功能

**Comment by iwtywai** [comment]
mailbox就是个缓冲区，和手机通讯的数据会存进去，up程序中的st25dv mailbox process就是处理它的

**Comment by TopRookie** [comment]
好的 谢谢 后边搜出来点东西了 &nbsp;
 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "iwtywai"<notifications@github.com&gt;; 
发送时间: 2020年7月23日(星期四) 上午10:42
收件人: "peng-zhihui/L-ink_Card"<L-ink_Card@noreply.github.com&gt;; 
抄送: "wo+"<564528143@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [peng-zhihui/L-ink_Card] 传输问题 (#66)





 mailbox就是个缓冲区，和手机通讯的数据会存进去，up程序中的st25dv mailbox process就是处理它的
