### ISSUE TITLE
安卓工程似乎安装不了运行系统有要求吗？

### ISSUE THREAD

**Issue by DukeHouse** [peng-zhihui/L-ink_Card#69]
对运行环境有要求吗？如题

**Comment by Leonwenbin** [comment]
> 对运行环境有要求吗？如题
我装了试了一下，APP是可以用的。你问的问题读起来不是那么好理解，标点符号又不收费，哈哈。

**Comment by DukeHouse** [comment]
抱歉，打字急了，我在安卓7.0和10.0上分别试过不可以运行显示包解析错误，很有可能是我操作有误，up是在什么版本测试的呢？非常感谢

**Comment by Leonwenbin** [comment]
> 抱歉，打字急了，我在安卓7.0和10.0上分别试过不可以运行显示包解析错误，很有可能是我操作有误，up是在什么版本测试的呢？非常感谢

我是andriod10.0

**Comment by DukeHouse** [comment]
好的，谢谢稚辉君，今天在小伙伴的手机上安装起来了，Android studio的模拟器貌似不太聪明的样子

**Comment by Leonwenbin** [comment]
> 好的，谢谢稚辉君，今天在小伙伴的手机上安装起来了，Android studio的模拟器貌似不太聪明的样子

哥们，俺不是稚晖君，俺也是粉丝哈哈哈

**Comment by DukeHouse** [comment]
头像认错了居然，大型误会现场，抱歉抱歉

**Comment by xseruer** [comment]
包解析错误，大概率是下载的文件不完整（以前手机浏览器下载apk老报这个错），建议用电脑下载 用adb install 安装。
注意：首次启动需要授权，否则会蹦掉。
