### ISSUE TITLE
这套可以复制公交卡吗

### ISSUE THREAD

**Issue by Pig-Brother** [peng-zhihui/L-ink_Card#73]

**Comment by Blueanr** [comment]
不可以，但是你可以把你手上公车卡的芯片抠出来放进去

**Comment by TaohongMaxwell** [comment]
理论上可以强行复制，但不一定能正常使用，风险很大，不建议复制公交卡。

**Comment by Queeneren** [comment]
手机都可以用nfc坐公交，为啥这个不行呢？麻烦具体说说

**Comment by Blueanr** [comment]
> 手机都可以用nfc坐公交，为啥这个不行呢？麻烦具体说说
这世上哪有这么多为什么不为什么的，这个项目就没有复制、克隆的功能！！不能复制！不能克隆！
这个项目就只是单纯的用一个开关切换两张卡片，两张m1卡的内容都还是通过其他外设读出key之后再写进去的！！屏幕、和手机的通信什么的只是锦上添花可有可无的功能，没有模拟卡的功能！！！
你要是真的非常非常非常非常想用这玩意儿刷公交，解决方案上面也给了，你把你公交卡的芯片扣出来焊在他的线圈上，你就能通过那个开关切换卡片！
到目前我还没听说过能破解CPU卡的，你用头来复制？
