### ISSUE TITLE
关于 NRST 引脚上拉电阻问题

### ISSUE THREAD

**Issue by CloverGit** [peng-zhihui/L-ink_Card#88]
通过阅读 [STM32L051K8 datasheet](https://www.st.com/resource/zh/datasheet/stm32l051k8.pdf) 第 84 页，发现在 图.27 中， NRST 引脚应该是有内部上拉，为什么在 L-ink Card 中又增加了一个阻值 10K 的外部上拉电阻 R6 呢?

**Comment by mojinpan** [comment]
这个一方面是习惯性的做法,不是所有的mcu都内置上拉的,而且加了上拉 也不会有太大问题,所以一般都没有预留.另外一方面虽然内置了上拉,但是外置上拉电阻配合对地的电容能构成一个对电源的低通滤波,对高频干扰和启动时的抖动有很好的抑制,所以加上可靠性一般会更好.总结下来就是加上电阻大概没有错,而且大不了可以不焊,所以大家都不一定仔细看规格书,直接默认加上
