### ISSUE TITLE
关于拨轮开关控制卡片切换的疑惑

### ISSUE THREAD

**Issue by wei762359599** [peng-zhihui/L-ink_Card#90]
你好  相请教一下卡片的切换是具体怎么通过拨轮开关控制的呢，通过看原理图，扳动拨轮开关只是将天线切换不用的连接，是对应ST25DV16K-JFR6D3芯片的AC0和AC1的是否连接来传输不同储存区的卡片信息吗？
表述的可能不是很清楚，但主要想知道通过拨轮开关切换卡片信息具体是怎么实现的。
希望看到的大佬们能够百忙之中抽时间解答一下这个疑惑。

**Comment by ZwenChen** [comment]
好像还需要加UID芯片才能刷卡，ST25DV只能与手机互传信息，我也不太明白可以私下交流一下。

**Comment by wei762359599** [comment]
> 好像还需要加UID芯片才能刷卡，ST25DV只能与手机互传信息，我也不太明白可以私下交流一下。

感谢  是这样的 一开始以为是可以用ST25DV来模拟卡
